Phase 1: Basics & Creation
Sab se pehlay NumPy library ko import krny ka standard tareeka aur ek simple 1D array banany ka code batao


In [5]:
import numpy as np

a = np.array([1,2,3])
print ( a)

[1 2 3]


Phase 2: Inspection & PlaceholdersFarz karo tumhare paas ek array hai, tum ye kaise check karoge ke uski shape kya hai aur us mein total number of elements kitne hain? Saath hi, ek aisa array banane ka code batao jis mein 3 rows aur 4 columns hon aur saare elements zero hon

In [11]:
print(a.shape)
print(len(a))

b = np.zeros((3,4))
print(b)

(3,)
3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Phase 3: Arithmetic & Reshaping
Agar tumhare paas do arrays hon a aur b, toh unko multiply krne ka command kya hai? 

Mere paas ek array g hai, main uski data ko badle baghair uski shape 3 rows aur 2 columns mein kaise change kr sakta ho?

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(np.multiply(a,b))

g = np.array([1,2,3,4,5,6,7,8,9,10])

print(g)
g_new = g.reshape(5, 2)
print(g_new)


[ 6 14 24 36 50]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Phase 4 check karte hain: Agar aap ko array k elements ko sort karna ho ya array ko reverse karna ho, toh kaunsi commands use hon gi?

In [23]:
a = np.array([10,4,8,9,3,5,2,7,1,6])

a.sort()
print(a)

print(a[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


Phase 4: Slicing & LogicAgar tumhare paas ek array b hai, toh tum 2nd row aur 3rd column ka element kaise select karoge?  Agar tumhe array a mein se sirf wo numbers nikalne hon jo 5 se baray ( > 5) hain, toh uska code kya hoga?

In [29]:
b = np.array([(1,2,3,4,5),(6,7,8,9,0),(9,8,7,6,5),(5,4,3,2,1)])

print(b)
print("Element at 2nd row and 3rd column", b[1,2])

print(b[b>5])

[[1 2 3 4 5]
 [6 7 8 9 0]
 [9 8 7 6 5]
 [5 4 3 2 1]]
Element at 2nd row and 3rd column 8
[6 7 8 9 9 8 7 6]


Phase 5: Aggregation & CombiningAgar tumhe array b ka mean (average) aur standard deviation nikalni ho, to kaunsi do commands use hogi? Mere paas do arrays hain: x = np.array([1,2]) aur y = np.array([3,4]). Inhein vertically stack (aik k neechay aik) karne ka code kya hoga? 

In [38]:
b = np.array([1,2,3,4,9,6,7,3,4,2])

print("MEAN =", b.mean())

x = np.array([1,2])
y = np.array([3,4])

print(np.vstack((x,y)))

MEAN = 4.1
[[1 2]
 [3 4]]


Phase 6: Advanced Manipulation & Splitting
Agar tumhare paas array b ho aur tum usay 3rd index se horizontally split karna chaho, toh kaunsi command use hogi? 



In [41]:
b = np.array([1,3,2,5,4,7,6,9,8])

print(np.hsplit(b,3))

print(np.std(b))

[array([1, 3, 2]), array([5, 4, 7]), array([6, 9, 8])]
2.581988897471611


Phase 7: Advanced Joining & Copies
Agar aapko array a ki aik aisi copy banani ho jo original array se bilkul alag (Deep Copy) ho, toh kaunsi command use hogi? 

Cheat sheet ke mutabiq, do arrays ko column-wise stack (jorhne) ke liye np.vstack ke ilawa konsi command di gayi hai?

In [56]:
a = np.array([1,2,3,4,5,6,7])
h = a.copy()

print("Printing a ",a)
print("Printing h ",h)
print("\n")
a[3] = 5555
print("\n")

print("Afet applying a.copy()")

print("Printing a after modifying: ",a)
print("Printing h after modifying a: ",h)

b = np.array([9,8,7,6,5])
i = np.copy(b)
print("\n")

print("Printing b ",b)
print("Printing i ",i)

b[3] = 333
print("\n")

print("Afet applying np.copy()")


print("Printing b ", b)
print("Printing i ",i)

j = b.view()
print("\n")

print("Afet applying b.view()")
print("Printing j ",j)

print("\n")

print(np.hstack((a,b)))

Printing a  [1 2 3 4 5 6 7]
Printing h  [1 2 3 4 5 6 7]




Afet applying a.copy()
Printing a after modifying:  [   1    2    3 5555    5    6    7]
Printing h after modifying a:  [1 2 3 4 5 6 7]


Printing b  [9 8 7 6 5]
Printing i  [9 8 7 6 5]


Afet applying np.copy()
Printing b  [  9   8   7 333   5]
Printing i  [9 8 7 6 5]


Afet applying b.view()
Printing j  [  9   8   7 333   5]


[   1    2    3 5555    5    6    7    9    8    7  333    5]


Phase 8: Universal Functions & Logic

Mere paas ek array a hai, mujhe uske har element ka Square Root nikalna hai aur Exponent (e^x) calculate karna hai. Iska tareeka kya hai?

Agar mujhe do arrays a aur b ko element-by-element compare karna ho ke wo barabar (equal) hain ya nahi, to kaunsi command use hogi?

In [66]:
a = np.array([1,2,3,4,5,6,7,9,10])

print("For printing square of each element")

result = np.sqrt(a)
print(result)

print("\n\nFor printing Exponent: ")
result = np.exp(a)
print(result)


print("\n\nComparing every element of 2 arrays: ")
a = np.array([1,2,3,4,5,6])
b = np.array([1,3,4,2,7,6])

print(a==b)


For printing square of each element
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 3.         3.16227766]


For printing Exponent: 
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 8.10308393e+03
 2.20264658e+04]


Comparing every element of 2 arrays: 
[ True False False False False  True]


Phase 9: Matrix Math (Machine Learning Base)
Machine Learning mein weights aur inputs ko multiply karne ke liye Dot Product use hota hai.

In [74]:
print("Taking dot product of 2 MATRICES:")

matrix1 = np.array([(1,2,3),
                    (4,5,6),
                    (7,8,9)])

matrix2 = np.array([(1,2,3),
                    (4,5,6),
                    (7,8,9)])

result = matrix1.dot(matrix2)

print(result)

print("\n\n")
print("Taking cross product")
result = matrix1*matrix2
print(result)



Taking dot product of 2 MATRICES:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]



Taking cross product
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Phase 10: Logic & Data Filtering

Boolean Indexing: Mere paas ek array data = np.array([10, 25, 40, 5, 15]) hai. Mujhe is mein se sirf wo numbers chahiye jo 20 se baray hon. Iska code kya hoga? 

Transposing: Machine Learning mein aksar hamein rows ko columns mein badalna parta hai (Matrix Transpose). Array b ko transpose karne ki do mukhtalif commands kaunsi hain? 

Unique Elements: (Bonus) Agar mujhe dekhna ho ke array mein kaun kaun se different numbers use hue hain, to np.unique() use hota hai. Lekin agar mujhe array ko flatten karna ho (yani multi-dimensional array ko simple 1D line mein badalna ho), to kaunsi command use hogi? 

In [85]:
a = np.array([10,25,40,5,15])

print(a>20)

matrix_a = np.array([(1,2,3),
                     (4,5,6),
                     (7,8,9)])

print("Simple matrix\n",matrix_a)
print("Transpose of matrix \n",np.transpose(matrix_a))

simple_1Darray = matrix_a.ravel()

print("\nConverting 2D array to 1D array\n")
print(simple_1Darray)




[False  True  True False False]
Simple matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of matrix 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Converting 2D array to 1D array

[1 2 3 4 5 6 7 8 9]


Phase 11: Joining & Splitting (The Final Boss)
Data ko manipulate karne ke liye ye tools bohat kaam aate hain:


Concatenate: Do arrays a aur d ko kisi specific axis par jorne ke liye konsi command use hogi? 


Vertical Split: Agar ek array ko vertically 2 hisson mein split karna ho, to konsi command use karenge?

In [96]:
a = np.array([1,2,3,4,5])
d = np.array([6,7,8,9,10])


print(np.concatenate((a,d),axis = 0))

print("\n\n",matrix1)
print(np.vsplit(matrix1,1))

[ 1  2  3  4  5  6  7  8  9 10]


 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
