In [3]:
# numpy core concept is array
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(b/a)



[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


In [4]:
# Array indexing or slicing
A = np.array([
    [1,2],
    [3,4]
])

print(A[0,1])
print(A[:,1])

2
[2 4]


In [6]:
# Matrix operation
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])

print(np.dot(A,B))
#Same as
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
print(np.random.rand(3,3)) # print a matrix of 3 b3 with random numbers
np.random.randint(0,10,4) # print 4 numberes between 0 - 10

[[0.55919252 0.54006976 0.79299809]
 [0.17344208 0.40702389 0.39702515]
 [0.46566647 0.25277417 0.33542732]]


array([3, 6, 1, 0], dtype=int32)

In [16]:
# Basic statistics:
a = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.mean(a))
print(np.std(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))


5.5
2.8722813232690143
55
10
1


In [18]:
# The most powerfull feature Broadcasting
a = np.array([1,2,3])

a+5

array([6, 7, 8])